version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: day2springboot
      MYSQL_USER: root
      MYSQL_PASSWORD: ********
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring_network

  springboot:
    build: .
    container_name: "springboot_container"
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/day2springboot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ********
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8081"
    networks:
      - spring_network

  networks:
    spring_network:
  volumes:
    mysql_data: